// let fn =function(){
//     btn.style.backgroundColor="green"

// }

// var btn=document.querySelector('button')
// btn.addEventListener('click',function(){
//     btn.textContent="starting in....."
    
//     btn.style.color="red"

// })

// btn.addEventListener('mouseover',fn)

// btn.addEventListener('mouseleave',function(){
//     btn.style.backgroundColor="#fff"
// })

// var head1=document.querySelector('h1')
// head1.addEventListener('dblclick',function(){
//     head1.textContent="DICE ACADEMY"
    
// })

var btns=document.querySelectorAll('button')
for(let i=0;i<btns.length;i++){
    if(btns.id=="button1"){
        
    btns[i].addEventListener('click',function(){
        btns[i].style.color='red'
    })

    }else if(btns.id=="button2"){

    // }else if (){

    }
    else{

    }

}


let arr=[[1,2,3][4,5,6][7,8,9]]


